version: 0.2

phases: 
  install: 
    commands: 
      - echo "Installing Node..."
      - curl -sL https://deb.nodesource.com/setup_12.x | bash
      - apt install -y nodejs

  pre_build: 
    commands: 
    - echo "Installing dependencies..."
    - yarn

  build: 
    commands: 
    - echo "Finalising..."
    - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build